//mockito test 2 from second tutorial, testing api.dart

// test/fetch_album_test.dart
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_testing_demo_and_code/api.dart';
import 'fetch_album_test.mocks.dart'; // Generated mock classes

@GenerateMocks([http.Client])
void main() {
  group('fetchAlbum', () {
    test('returns an Album if the HTTP call completes successfully', () async {
      final client = MockClient(); // MockClient is generated by Mockito
      // Stub the client's GET method to return a successful response (HTTP 200)
      when(
        client.get(Uri.parse('https://jsonplaceholder.typicode.com/albums/1')),
      ).thenAnswer(
        (_) async =>
            http.Response('{"userId": 1, "id": 1, "title": "Test Album"}', 200),
      );

      // Act: call the function under test
      final album = await fetchAlbum(client);

      // Assert: verify the result is an Album with the expected content
      expect(album.title, equals('Test Album'));
      expect(album.id, equals(1));
      // (We could also use expect(album, isA<Album>()), but checking fields is more thorough)

      // Verify that the client.get was called exactly once with the correct URL
      verify(
        client.get(Uri.parse('https://jsonplaceholder.typicode.com/albums/1')),
      ).called(1);
    });

    test(
      'throws an Exception if the HTTP call completes with an error',
      () async {
        final client = MockClient();
        // Stub the client to return a 404 response (or we could simulate an exception)
        when(
          client.get(
            Uri.parse('https://jsonplaceholder.typicode.com/albums/1'),
          ),
        ).thenAnswer((_) async => http.Response('Not Found', 404));

        // Act & Assert: calling fetchAlbum should throw an Exception
        expect(fetchAlbum(client), throwsException);

        // Optionally verify the call was made once
        verify(
          client.get(
            Uri.parse('https://jsonplaceholder.typicode.com/albums/1'),
          ),
        ).called(1);
      },
    );
  });
}
